[package]
name = "musicos"
edition = "2024"
license = "Apache 2.0"
authors = ["Unconfirmed Labs, LLC (os@unconfirmed.com)"]

[dependencies]
interest_bps = { r.mvr = "@interest/bps" }
language_code = { git = "https://github.com/unconfirmedlabs/language_code.git", rev = "main" }
walrus_data = { git = "https://github.com/unconfirmedlabs/walrus_data.git", rev = "main" }
