[package]
name = "musicos"
edition = "2024"
license = "Apache 2.0"
authors = ["Subsonic Labs, LLC (os@unconfirmed.com)"]

[dependencies]
interest_bps = { r.mvr = "@interest/bps" }
gengo = { git = "https://github.com/unconfirmedlabs/gengo.git", rev = "main" }
ori = { git = "https://github.com/unconfirmedlabs/ori.git", rev = "main" }
