[package]
name = "musicos"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Studio Mirai, LLC"]

[dependencies]
interest_bps = { local = "../../../interest-mvr/bps" }
language_code = { local = "../../../language_code" }
walrus_data = { local = "../../../walrus_data" }

[environments]
mirainet = "11235922"