[package]
name = "share"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Sona Labs, Inc. (build@sonamusic.com)"]

[dependencies]

[addresses]
share = "0x0"
initializer = "0x34eb10e44c0b17b1eb95f59857f2a202eb77cf8ac6697f56d6dbf364f8bebe8e"