[package]
name = "share"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Sona Labs, Inc. (musicos@sonamusic.com)"]

[dependencies]

[addresses]
share = "0x0"
initializer = "0x634a3508e2c419dac9ec53eab917fb3f3886ff111c18cf13aabe48b48c2a9ccd"