[package]
name = "share_currency_template"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]

[addresses]
share = "0x0"
initializer = "0x634a3508e2c419dac9ec53eab917fb3f3886ff111c18cf13aabe48b48c2a9ccd"