[package]
name = "Music"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Sona Labs, Pte Ltd (build@sonamusic.com)"]

[dependencies]
CurrencyTreasury = { local = "../../../../currency_treasury" }

[addresses]
music = "0x0"