[package]
name = "music"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Sona Labs, Inc (build@sonamusic.com)"]

[dependencies]
currency_treasury = { local = "../../../../currency_treasury" }

[environments]
mirainet = "dd32b170"
