[package]
name = "musicos"
edition = "2024"
license = "Apache 2.0"
authors = ["Unconfirmed Labs, Inc. (os@unconfirmed.com)"]

[dependencies]
bps = { git = "https://github.com/unconfirmedlabs/bps.git", rev = "main" }
gengo = { git = "https://github.com/unconfirmedlabs/gengo.git", rev = "main" }
ori = { git = "https://github.com/unconfirmedlabs/ori.git", subdir = "move", rev = "main" }
partyos = { git = "https://github.com/unconfirmedlabs/partyos.git", rev = "main" }
share = { git = "https://github.com/unconfirmedlabs/share.git", rev = "main" }
