[package]
name = "music"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]

[addresses]
music = "0x0"