[package]
name = "composition_reward_pool"
edition = "2024"
license = "Apache 2.0"
authors = ["Studio Mirai, LLC (build@sm.xyz)"]

[dependencies]
musicos = { local = "../../musicos" }
reward_pool = { local = "../../../../reward_pool" }