[package]
name = "miso"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (os@miso.network)"]

[dependencies]
bps = { git = "https://github.com/unconfirmedlabs/bps.git", rev = "main" }
share = { local = "../lib/share" }
