[package]
name = "composition_recording_stake"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (os@miso.network)"]

[dependencies]
miso = { local = "../../core" }
hikida = { git = "https://github.com/unconfirmedlabs/hikida.git", rev = "main" }
royalty_pool = { git = "https://github.com/unconfirmedlabs/royalty-pool.git", subdir = "move", rev = "main" }
