[package]
name = "MusicOS"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Sona Labs, Inc. (build@sonamusic.com)"]

[dependencies]
CurrencyTreasury = { git = "https://github.com/studio-mirai/currency_treasury.git", rev = "main" }
InterestBPS = { local = "../../../miraicloud/mirainet/interest-mvr/bps" }
InterestMath = { local = "../../../miraicloud/mirainet/interest-mvr/math" }
MUSIC = { local = "../coins/music" }

[addresses]
musicos = "0x0"
admin = "0xf3a64ba48423dccce1b0e09f33984e88a8649a2aad0bfbd90ef5b3127f065d8d"