[package]
name = "musicos"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["Coda Labs, Pte Ltd (os@coda.network)"]

[dependencies]
interest_bps = { r.mvr = "@interest/bps" }

[addresses]
musicos = "0x0"